# Page settings
baseurl      = "https://shklinkenberg.github.io/"
# relativeURLs = true
title        = "TestVision Gebruikersgroep"
languageCode = "en-us"
theme        = "hugo-elate-theme"
enableEmoji  = true
publishDir   = "docs"
ignoreFiles  = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author      = "Klinkenberg"
  description = "Website van de TestVision gebruikersgroep"
  email       = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand        = "TVG"
    home         = "Home"
    work         = "Work"
    testimonials = "Testimonials"
    services     = "Doelen"
    about        = "Kernteam"
    contact      = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title    = "TestVision Gebruikersgroep"
    subtitle = 'De Nederlandse TestVision gebruikersgroep wordt gerund door gebruikers van TestVision en is toegankelijk voor alle<br> gebruikers.<br><br>Meld je hieronder aan om op onze mailinglijst te komen.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title       = "Events"
    description = "Overzicht van onze evenementen."
    url         = "events"
    button      = "Events"
    icon        = "icon-calendar"
    img         = "img_8.jpg"
    
  [[params.intro.item]]
    title       = "Mailinglijst"
    description = "Je kan je hier aanmelden voor de mailinglijst. Zo kan je vragen stellen aan de community."
    url         = "https://nlpsych.eu.qualtrics.com/jfe/form/SV_cMezO6LbJPOLO8l"
    button      = "Aanmelden"
    icon        = "icon-envelope"
    img         = "img_7.jpg"

  [[params.intro.item]]
    title       = "Testvision"
    description = "Directe link naar de website van TestVision.    "
    url         = "https://www.testvision.nl"
    button      = "TVO"
    icon        = "icon-globe"
    img         = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = false
    title = "Work"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Branding"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Design"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Design"

  # Services section
  [params.services]
    enable = true
    title = "Doelen"
    description = "De TestVision Gebruikersgroep is, na de opheffing van de TestVison Gebruikers Vereniging, in september 2019 in het leven geroepen. De verenigingsstructuur was niet meer geheel van deze tijd en was tevens wat te beperkt in haar toegankelijkheid. Met de Gebruikersgroep, die voor alle TestVision gebruikers toegankelijk is, hopen we een veel grotere groep mensen te kunnen betrekken. Onze doelen zijn hieronder weergegeven."

    [[params.services.item]]
      title = "Kennisdeling"
      description = "TestVision biedt vele mogelijkheden van implementatie. Van individueel gebruik tot beperkte toegang voor bepaalde rollen binnen de organisatie. Zien hoe bij anderen deze inrichtingskeuzes worden gemaakt is vaak zeer verhelderend. De TestVision Gebruikersgroep is er om deze informatie middels evenementen en de mailinglijst te delen."
      icon = "icon-people"

    [[params.services.item]]
      title = "Advies"
      description = "Zoals bij alle SaaS oplossingen, doet het niet altijd wat je wil. De TestVision Gebruikersgroep is er om Teelen te adviseren over de mogelijkheden voor de roadmap."
      icon = "icon-target"
      
    [[params.services.item]]
      title = "Bedrijven"
      description = "De behoeften van commerciële gebruikers van TestVision lopen zeer uiteen, van inhouse assessment tot externe certificering. Ieder doel kent zijn eigen werkwijze. De TestVision Gebruikersgroep is er om ervaringen te delen en behoeften zichtbaar te maken."
      icon = "icon-graph"

    [[params.services.item]]
      title = "Onderwijsinstellingen"
      description = "De behoeften van onderwijsinstellingen verschillen van die uit het bedrijfsleven en zijn ook meer divers. De TestVision Gebruikersgroep is er om inzichten te delen en om behoeften in kaart te brengen."      
      icon = "icon-university"

  # About section
  [params.about]
    enable = true
    title = "Kernteam"
    description = "Het kernteam van de TestVision Gebruikersgroep bestaat uit:"

    [[params.about.item]]
      name = "Sharon Klinkenberg"
      position = "Voorzitter"
      description = "Instelling: Universiteit van Amsterdam"
      img = "SharonKlinkenberg.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "https://twitter.com/shklinkenberg"],
        ["icon-linkedin", "https://www.linkedin.com/in/sharonklinkenberg/"],
        ["icon-globe", "http://www.klinkenberg.amsterdam"]
      ]

    [[params.about.item]]
      name = "Joris van Kampen"
      position = "Kernteamlid"
      description = "Instelling: Hogeschool van Amsterdam"
      img = "Joris.jpeg"
      alt = "Person2"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/jorisvankampen/"]
      ]
      
      [[params.about.item]]
      name = "  Ilse Kröse"
      position = "Kernteamlid"
      description = "Instelling: Breda University of Applied Sciences"
      img = "Ilse.jpeg"
      alt = "Person2"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/ilse-kröse-a9a7825/?originalSubdomain=nl"]
      ]

      [[params.about.item]]
      name = "  Deborah Zwaan Huijsman"
      position = "Kernteamlid"
      description = "Instelling: Vrije Universiteit Amsterdam"
      img = "Deborah.jpeg"
      alt = "Person2"
      social = [
        ["icon-linkedin", "https://www.linkedin.com/in/deborah-zwaan-huijsman-1b8b0686/"]
      ]

    [[params.about.item]]
      name = "Annie van Schaik-Jorritsma"
      position = "Kernteamlid"
      description = "Bedrijf: CZ Zorgverzekeraar"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-globe", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Leden"
      icon = "icon-people"
      from = 0
      to = 169
      interval = 1
      speed = 1000

    [[params.counters.item]]
      description = "Bedrijven"
      icon = "icon-graph"
      from = 0
      to = 24
      interval = 1
      speed = 1000

    [[params.counters.item]]
      description = "Onderwijsinstellingen"
      icon = "icon-university"
      from = 0
      to = 26
      interval = 1
      speed = 1000

#    [[params.counters.item]]
#      description = "Happy clients"
#      icon = "icon-people"
#      from = 0
#      to = 52
#      interval = 50
#      speed = 1000

  # Contact section
  [params.contact]
    enable = false
    map = false
    form = false
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
